apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-xmlstilling-admin
  namespace: default
  labels:
    team: teampam
spec:
  image: repo.adeo.no:5443/pam-xmlstilling-admin
  port: 9024
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  liveness:
    initialDelay: 60
    path: /isAlive
  readiness:
    initialDelay: 60
    path: /isAlive
  webproxy: true
  vault:
    enabled: true
  ingresses:
  - https://pam-xmlstilling-admin.nais.adeo.no
  - https://pam-xmlstilling-admin.adeo.no
