apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-xmlstilling-admin
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9024
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  liveness:
    path: /isAlive
    initialDelay: 20
  readiness:
    path: /isAlive
    initialDelay: 20
  vault:
    enabled: true
  webproxy: false
  prometheus:
    enabled: true
    path: /prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
